
version: '3.0'
services:
  web:
    # TODO: build context, ports and redis dependency
    build:
      context: .
    volumes:
      - .:/code
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 5000
  redis:
    image: redis:6.0-rc4-alpine
    ports: 
     - 5000:5000
    volumes:
     - $PWD/redis-data:/data
    # TODO: missing persistence for redis. You need to persist /data directory.

